"""add account members and invites

Revision ID: a1b2c3d4e5f6
Revises: 1f5abb10532b
Create Date: 2026-08-20 16:55:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '1f5abb10532b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_members',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('account_id', 'user_id')
    )
    with op.batch_alter_table('account_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_members_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_members_user_id'), ['user_id'], unique=False)

    op.create_table('account_invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_by', sa.Uuid(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('account_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_invites_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_invites_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_invites_token'), ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_invites_token'))
        batch_op.drop_index(batch_op.f('ix_account_invites_email'))
        batch_op.drop_index(batch_op.f('ix_account_invites_account_id'))

    op.drop_table('account_invites')
    with op.batch_alter_table('account_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_account_members_account_id'))

    op.drop_table('account_members')
    # ### end Alembic commands ###