"""add telegram fields to users

Revision ID: a8d60a23c911
Revises: f6a7b8c9d0e1
Create Date: 2026-08-26 11:22:50.652213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d60a23c911'
down_revision = 'f6a7b8c9d0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('telegram_username', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('telegram_first_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('telegram_last_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('telegram_photo_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('telegram_link_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('telegram_link_token_expires', sa.DateTime(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_telegram_link_token'), ['telegram_link_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_link_token'))
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('telegram_link_token_expires')
        batch_op.drop_column('telegram_link_token')
        batch_op.drop_column('telegram_photo_url')
        batch_op.drop_column('telegram_last_name')
        batch_op.drop_column('telegram_first_name')
        batch_op.drop_column('telegram_username')
        batch_op.drop_column('telegram_id')

    # ### end Alembic commands ###
